name: Anti-Bot
authors: [filippop1, TheMolkaPL]
version: '${project.version}'
description: 'Blokowanie botów na serwerze Minecraft'
website: 'https://github.com/Thefilippop1PL/Anti-Bot'
main: pl.filippop1.antibot.AntiBotPlugin
